### ISSUE TITLE
Pass argument to JSON that is passed to callback

### ISSUE THREAD

**Issue by injamies** [pantor/inja#212]
I am trying to pass custom JSON to callback that needs to include argument `(var)` inside the JSON, but I can't get it to work. Here's the example:

```cpp
environment.add_void_callback("callback", 1, [](inja::Arguments &args) {
   nlohmann::json json = args.at(0) -> get<nlohmann::json>();
   std::cout << json << std::endl;
});

{% set var = "example" %}

{{
   callback({
      "var": {{ var }}
   )}
}}


```

**Comment by pantor** [comment]
Hi @injamies, this is currently not supported (and probably won't be in the foreseeable future). The reason for that is that I hesitate to implement my own json parser into inja, as this is quite difficult and error-prone. Anyway, you could mitigate that issue by adapting your callback method in your example case.

And indeed @eclarkso, this issue is the same as #151, so I'll close this for now.
