### ISSUE TITLE
Performance problem of inja

### ISSUE THREAD

**Issue by xmh0511** [pantor/inja#62]
When I try to render 200 data with inja, the inja processing takes a long time. It takes about 9 seconds. I hope inja can improve the performance problem.

**Comment by ludekvodicka** [comment]
Unfortunately on large datasets the performance is much worse ;-(. 

I already reported this too but I'm affraid it would be necessary to rewrite a lot of parts of inja to improve it.

**Comment by xmh0511** [comment]
The test results are as follows
![_ _20180831165217](https://user-images.githubusercontent.com/17973891/44903164-62aeca80-ad3e-11e8-93e2-668b7561d3ef.png)
The test data size is 1133
use boost:timer to record time
![_ _20180831165501](https://user-images.githubusercontent.com/17973891/44903260-9f7ac180-ad3e-11e8-99af-a554b91428c2.png)

**Comment by xmh0511** [comment]
@ludekvodicka  Thanks, inja is easy to use, but it takes a long time to render a lot of data. I think this should focus on improving, inja will be better.

**Comment by xmh0511** [comment]
@ sorry ,i tested 1133 data ,these data are large ,tested in release build

**Comment by xmh0511** [comment]
@flexferrum sorry ,i tested 1133 data ,these data are large ,tested in release build

**Comment by ludekvodicka** [comment]
The problem occurs when there is a larger template (for example the whole HTML page) with several sub-pages. From what I measured it was caused by slow regexes when searching in a large input template. 

I believe that the problem is that there are too many regex searches which are repetitively tested against a large string. This takes a lot of time.

I think it will be better to have some stream parser instead of that. But this would need a complete rewrite of the library. 

It's been some time when I worked with inja. I needed it for one our internal project where we're generating reports. For large reports, it takes up to 60second to generate it. In comparing with old ctemplate library the same task takes 5sec max. 

But inja is much better for template definition and current performance isn't a huge issue for us, so we stay with Inja.

**Comment by flexferrum** [comment]
This amount of data gives me 532 msec in virtual environment of codenvy.io. That's big enough.

**Comment by flexferrum** [comment]
> I believe that the problem is that there are too many regex searches which are repetitively tested against a large string. This takes a lot of time.

As you can see, in this case the template is pretty simple. So, perhaps the problem is in regex search, but personally I'm not sure. I think, json engine usage gives you runtime penalty as well. 

> I think it will be better to have some stream parser instead of that. But this would need a complete rewrite of the library.

If you simply split template rendering process onto the two phases: parsing and rendering itself, it will give you three-fold boost in this sample. 532 msecs against 5. But you right, in this case library should be completely rewritten from the scratch.

**Comment by ludekvodicka** [comment]
Yes, splitting template processing to two phases would be great. It's something I already discuss with author but for now this is unfortunately not possible.

**Comment by PeterJohnson** [comment]
I recently did a from-scratch rewrite that fixes the performance issues: wpilibsuite/allwpilib#1487 .  I handwrote a lexer and recursive descent parser to perform the parsing phase, and a stack-based machine to execute rendering.  I used LLVM classes in the rewrite such as StringRef and SmallString to avoid heap allocation wherever possible, and made it separate .cpp and .h files, but even so, it shouldn't be too hard for someone to backport into this style of header only library.

**Comment by flexferrum** [comment]
@PeterJohnson, you did something similar that I've done.

**Comment by pantor** [comment]
This is in master now. Thanks all!
